#!/bin/sh

html_dir=/var/www/html

local_repo_dir="$html_dir/repos/github/hackforla/shared-housing"
local_repo_src="$html_dir/repos/github/hackforla/shared-housing/projects/tomdemo"
local_repo_branch="tomdemo"

cd $local_repo_dir && git checkout "$branch" && git pull --rebase

deploy_html_dir="$html"
deploy_organization="lafh"
deploy_project="tomdemo"
deploy_dst="$html/$deploy_organization/$deploy_project/"

rsync -av --delete $local_repo_src $deploy_dst
